title: Posts
description: I write to forget.
author: hyejong
github: https://github.com/hyejong
about: Everything is Fine.
disqus_shortname: https-github-com-hyejong
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/hyejong.hong"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/hyejong/"
    - icon: fa-github
      link: "https://github.com/hyejong"

urls:
    - text: Category
      url: /category/go
    - text: About Me
      url: /about/

url: "https://hyejong.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
